version: '3.3'
services:
  glide:
    image: ghcr.io/einstack/glide:latest-alpine
    command: --config /bin/config.yaml
    ports:
      - 9099:9099
    volumes:
      - ./config.yaml:/bin/config.yaml
      - ./secrets/:/bin/secrets/
